//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class GebakophetWerkEntities : DbContext
{
    public GebakophetWerkEntities()
        : base("name=GebakophetWerkEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Order> Orders { get; set; }
    public DbSet<OrderPie> OrderPies { get; set; }
    public DbSet<Pie> Pies { get; set; }
    public DbSet<User> Users { get; set; }

    public virtual ObjectResult<AlleBestellingen_Result> AlleBestellingen()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlleBestellingen_Result>("AlleBestellingen");
    }

    public virtual ObjectResult<AlleKlanten_Result> AlleKlanten()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlleKlanten_Result>("AlleKlanten");
    }

    public virtual ObjectResult<Tebakkentaarten_Result> Tebakkentaarten()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tebakkentaarten_Result>("Tebakkentaarten");
    }

    public virtual ObjectResult<Nullable<decimal>> GetCakePrice(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetCakePrice", iDParameter);
    }

    public virtual ObjectResult<Nullable<int>> GetOrderIdList(Nullable<int> userID)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetOrderIdList", userIDParameter);
    }

    public virtual ObjectResult<GetTaartenList_Result> GetTaartenList()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTaartenList_Result>("GetTaartenList");
    }
}
